"""Pass@K evaluation service for assessing SQL generation quality."""
import asyncio
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from sqlalchemy.ext.asyncio import AsyncEngine

from app.core.logging import get_logger
from app.services.nl2sql import generate_sql
from app.services.sql_checker import ErrorType, ExecutionCheckResult, SQLChecker

logger = get_logger(__name__)


@dataclass
class CandidateSQL:
    """A candidate SQL generated by sampling."""

    sql: str
    confidence: float = 0.0
    execution_success: bool = False
    is_correct: Optional[bool] = None
    error_type: Optional[ErrorType] = None
    error_message: Optional[str] = None
    execution_time_ms: Optional[float] = None
    row_count: Optional[int] = None


@dataclass
class PassAtKMetrics:
    """Metrics for Pass@K evaluation."""

    k: int
    pass_at_k: float  # Probability that at least one is correct
    correct_count: int  # Number of correct SQLs
    executable_count: int  # Number of executable SQLs
    total_count: int  # Total number of candidates
    majority_vote_sql: Optional[str] = None  # SQL selected by majority voting
    majority_vote_count: int = 0  # Vote count for majority


@dataclass
class PassAtKResult:
    """Complete result of Pass@K evaluation."""

    success: bool
    question: str
    gold_sql: Optional[str]
    candidates: List[CandidateSQL]
    metrics: Optional[PassAtKMetrics] = None
    error_message: Optional[str] = None
    execution_time_ms: Optional[float] = None


class PassAtKEvaluator:
    """Pass@K evaluator for SQL generation assessment.

    This class implements the Pass@K metric which measures the probability
    that at least one out of K sampled SQL queries is correct.

    Reference: "Pass@k" metric from CodeX paper (Chen et al., 2021)
    """

    def __init__(
        self,
        checker: SQLChecker,
        max_workers: int = 4,
        timeout_seconds: float = 30.0,
    ):
        """Initialize Pass@K evaluator.

        Args:
            checker: SQLChecker instance for validation.
            max_workers: Maximum parallel workers for execution.
            timeout_seconds: Timeout for SQL execution.
        """
        self.checker = checker
        self.max_workers = max_workers
        self.timeout_seconds = timeout_seconds

    async def generate_k(
        self,
        question: str,
        schema_text: str,
        k: int,
        provider: str = "openai",
        model_config: Optional[Dict[str, Any]] = None,
        dialect: str = "MySQL",
        api_key: Optional[str] = None,
        format_type: str = "openai",
        base_url: Optional[str] = None,
        temperature: float = 0.7,
    ) -> List[str]:
        """Generate K candidate SQL queries using sampling.

        Args:
            question: Natural language question.
            schema_text: Database schema in text format.
            k: Number of candidates to generate.
            provider: LLM provider name.
            model_config: Model configuration.
            dialect: SQL dialect.
            api_key: API key for the provider.
            format_type: API format type.
            base_url: Custom base URL.
            temperature: Sampling temperature (should be > 0 for diversity).

        Returns:
            List of K candidate SQL queries.
        """
        if k <= 0:
            raise ValueError("k must be positive")

        # Update model config with temperature for sampling
        config = dict(model_config) if model_config else {}
        config["temperature"] = temperature

        # Generate K candidates in parallel
        tasks = [
            generate_sql(
                question=question,
                schema_text=schema_text,
                provider=provider,
                model_config=config,
                dialect=dialect,
                api_key=api_key,
                format_type=format_type,
                base_url=base_url,
            )
            for _ in range(k)
        ]

        try:
            results = await asyncio.gather(*tasks, return_exceptions=True)

            candidates = []
            for i, result in enumerate(results):
                if isinstance(result, Exception):
                    logger.warning(f"Candidate {i+1} generation failed: {result}")
                    continue
                candidates.append(result)

            logger.info(f"Generated {len(candidates)}/{k} candidates successfully")
            return candidates

        except Exception as e:
            logger.error(f"Failed to generate candidates: {e}")
            return []

    async def evaluate(
        self,
        candidates: List[str],
        engine: AsyncEngine,
        gold_sql: Optional[str] = None,
    ) -> List[CandidateSQL]:
        """Evaluate K candidate SQL queries.

        Executes each candidate and checks correctness against gold SQL.

        Args:
            candidates: List of candidate SQL queries.
            engine: SQLAlchemy async engine.
            gold_sql: Optional gold SQL for correctness comparison.

        Returns:
            List of CandidateSQL with evaluation results.
        """
        if not candidates:
            return []

        # Create semaphore to limit concurrent execution
        semaphore = asyncio.Semaphore(self.max_workers)

        async def evaluate_one(sql: str) -> CandidateSQL:
            async with semaphore:
                return await self._evaluate_single(sql, engine, gold_sql)

        # Evaluate all candidates in parallel with limited concurrency
        tasks = [evaluate_one(sql) for sql in candidates]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        evaluated = []
        for i, result in enumerate(results):
            if isinstance(result, Exception):
                logger.warning(f"Candidate {i+1} evaluation failed: {result}")
                evaluated.append(CandidateSQL(
                    sql=candidates[i],
                    execution_success=False,
                    error_type=ErrorType.EXECUTION_ERROR,
                    error_message=str(result),
                ))
            else:
                evaluated.append(result)

        return evaluated

    async def _evaluate_single(
        self,
        sql: str,
        engine: AsyncEngine,
        gold_sql: Optional[str] = None,
    ) -> CandidateSQL:
        """Evaluate a single candidate SQL.

        Args:
            sql: Candidate SQL query.
            engine: SQLAlchemy async engine.
            gold_sql: Optional gold SQL for comparison.

        Returns:
            CandidateSQL with evaluation results.
        """
        # Check syntax first
        syntax_result = await self.checker.check_syntax(sql)
        if not syntax_result.is_valid:
            return CandidateSQL(
                sql=sql,
                execution_success=False,
                is_correct=False,
                error_type=syntax_result.error_type,
                error_message=syntax_result.error_message,
            )

        # Execute and check
        exec_result = await self.checker.check_execution(
            sql=sql,
            engine=engine,
            timeout=self.timeout_seconds,
            gold_sql=gold_sql,
        )

        return CandidateSQL(
            sql=sql,
            execution_success=exec_result.success,
            is_correct=exec_result.success if gold_sql else None,
            error_type=exec_result.error_type,
            error_message=exec_result.error_message,
            execution_time_ms=exec_result.execution_time_ms,
            row_count=exec_result.row_count,
        )

    def calculate_metrics(
        self,
        candidates: List[CandidateSQL],
        k: int,
    ) -> PassAtKMetrics:
        """Calculate Pass@K metrics.

        The Pass@K metric is calculated as:
        pass_at_k = 1 - (C(n-c, k) / C(n, k))
        where n = total candidates, c = correct candidates

        For computational efficiency with sampling without replacement:
        pass_at_k = 1 - ((n-c) choose k) / (n choose k)

        With replacement approximation (for large n):
        pass_at_k ≈ 1 - (1 - c/n)^k

        Args:
            candidates: List of evaluated candidates.
            k: K value for Pass@K.

        Returns:
            PassAtKMetrics with calculated metrics.
        """
        if not candidates or k <= 0:
            return PassAtKMetrics(
                k=k,
                pass_at_k=0.0,
                correct_count=0,
                executable_count=0,
                total_count=len(candidates),
            )

        n = len(candidates)
        c = sum(1 for cand in candidates if cand.is_correct)
        executable = sum(1 for cand in candidates if cand.execution_success)

        # Calculate Pass@K using the formula
        # pass_at_k = 1 - (1 - c/n)^k  (with replacement approximation)
        if n > 0 and c > 0:
            pass_at_k = 1 - (1 - c / n) ** min(k, n)
        else:
            pass_at_k = 0.0

        # Perform majority voting
        majority_sql, vote_count = self._majority_vote(candidates)

        return PassAtKMetrics(
            k=k,
            pass_at_k=pass_at_k,
            correct_count=c,
            executable_count=executable,
            total_count=n,
            majority_vote_sql=majority_sql,
            majority_vote_count=vote_count,
        )

    def _majority_vote(
        self,
        candidates: List[CandidateSQL],
    ) -> Tuple[Optional[str], int]:
        """Select best SQL using majority voting based on execution results.

        Groups candidates by their execution results and selects the most common.

        Args:
            candidates: List of evaluated candidates.

        Returns:
            Tuple of (selected_sql, vote_count).
        """
        if not candidates:
            return None, 0

        if len(candidates) == 1:
            return candidates[0].sql, 1

        # Group by execution result signature
        # Use (execution_success, row_count, error_type) as signature
        result_groups: Dict[str, List[CandidateSQL]] = {}

        for cand in candidates:
            if not cand.execution_success:
                # Group by error type for failed executions
                signature = f"error:{cand.error_type or 'unknown'}"
            else:
                # Group by row count for successful executions
                signature = f"success:{cand.row_count or 0}"

            if signature not in result_groups:
                result_groups[signature] = []
            result_groups[signature].append(cand)

        if not result_groups:
            return candidates[0].sql, 1

        # Find the group with most votes
        best_signature = max(result_groups.keys(), key=lambda s: len(result_groups[s]))
        best_group = result_groups[best_signature]
        vote_count = len(best_group)

        # Return the first SQL from the best group
        return best_group[0].sql, vote_count

    async def run(
        self,
        question: str,
        schema_text: str,
        engine: AsyncEngine,
        k: int = 8,
        gold_sql: Optional[str] = None,
        provider: str = "openai",
        model_config: Optional[Dict[str, Any]] = None,
        dialect: str = "MySQL",
        api_key: Optional[str] = None,
        format_type: str = "openai",
        base_url: Optional[str] = None,
        temperature: float = 0.7,
    ) -> PassAtKResult:
        """Run complete Pass@K evaluation pipeline.

        Args:
            question: Natural language question.
            schema_text: Database schema in text format.
            engine: SQLAlchemy async engine.
            k: Number of candidates to generate.
            gold_sql: Optional gold SQL for correctness comparison.
            provider: LLM provider name.
            model_config: Model configuration.
            dialect: SQL dialect.
            api_key: API key for the provider.
            format_type: API format type.
            base_url: Custom base URL.
            temperature: Sampling temperature.

        Returns:
            PassAtKResult with complete evaluation results.
        """
        import time

        start_time = time.time()

        try:
            # Step 1: Generate K candidates
            logger.info(f"Generating {k} candidates for Pass@K evaluation")
            candidate_sqls = await self.generate_k(
                question=question,
                schema_text=schema_text,
                k=k,
                provider=provider,
                model_config=model_config,
                dialect=dialect,
                api_key=api_key,
                format_type=format_type,
                base_url=base_url,
                temperature=temperature,
            )

            if not candidate_sqls:
                return PassAtKResult(
                    success=False,
                    question=question,
                    gold_sql=gold_sql,
                    candidates=[],
                    error_message="Failed to generate any candidates",
                )

            # Step 2: Evaluate candidates
            logger.info(f"Evaluating {len(candidate_sqls)} candidates")
            evaluated_candidates = await self.evaluate(
                candidates=candidate_sqls,
                engine=engine,
                gold_sql=gold_sql,
            )

            # Step 3: Calculate metrics
            metrics = self.calculate_metrics(evaluated_candidates, k)

            execution_time_ms = (time.time() - start_time) * 1000

            logger.info(
                f"Pass@K evaluation complete: "
                f"pass_at_{k}={metrics.pass_at_k:.2%}, "
                f"correct={metrics.correct_count}/{metrics.total_count}"
            )

            return PassAtKResult(
                success=True,
                question=question,
                gold_sql=gold_sql,
                candidates=evaluated_candidates,
                metrics=metrics,
                execution_time_ms=execution_time_ms,
            )

        except Exception as e:
            logger.error(f"Pass@K evaluation failed: {e}")
            execution_time_ms = (time.time() - start_time) * 1000

            return PassAtKResult(
                success=False,
                question=question,
                gold_sql=gold_sql,
                candidates=[],
                error_message=str(e),
                execution_time_ms=execution_time_ms,
            )

    async def run_with_existing_candidates(
        self,
        candidate_sqls: List[str],
        question: str,
        engine: AsyncEngine,
        k: int = 8,
        gold_sql: Optional[str] = None,
    ) -> PassAtKResult:
        """Run Pass@K evaluation with existing candidate SQLs.

        Args:
            candidate_sqls: Pre-generated candidate SQL queries.
            question: Natural language question.
            engine: SQLAlchemy async engine.
            k: K value for Pass@K.
            gold_sql: Optional gold SQL for comparison.

        Returns:
            PassAtKResult with evaluation results.
        """
        import time

        start_time = time.time()

        try:
            if not candidate_sqls:
                return PassAtKResult(
                    success=False,
                    question=question,
                    gold_sql=gold_sql,
                    candidates=[],
                    error_message="No candidates provided",
                )

            # Evaluate candidates
            logger.info(f"Evaluating {len(candidate_sqls)} candidates")
            evaluated_candidates = await self.evaluate(
                candidates=candidate_sqls,
                engine=engine,
                gold_sql=gold_sql,
            )

            # Calculate metrics
            metrics = self.calculate_metrics(evaluated_candidates, k)

            execution_time_ms = (time.time() - start_time) * 1000

            return PassAtKResult(
                success=True,
                question=question,
                gold_sql=gold_sql,
                candidates=evaluated_candidates,
                metrics=metrics,
                execution_time_ms=execution_time_ms,
            )

        except Exception as e:
            logger.error(f"Pass@K evaluation failed: {e}")
            execution_time_ms = (time.time() - start_time) * 1000

            return PassAtKResult(
                success=False,
                question=question,
                gold_sql=gold_sql,
                candidates=[],
                error_message=str(e),
                execution_time_ms=execution_time_ms,
            )
