"""Rename key_type to provider

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-03-13 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old index
    op.drop_index('ix_api_keys_key_type', table_name='api_keys')

    # Rename the column
    op.alter_column('api_keys', 'key_type', new_column_name='provider')

    # Create the new index
    op.create_index('ix_api_keys_provider', 'api_keys', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new index
    op.drop_index('ix_api_keys_provider', table_name='api_keys')

    # Rename the column back
    op.alter_column('api_keys', 'provider', new_column_name='key_type')

    # Create the old index
    op.create_index('ix_api_keys_key_type', 'api_keys', ['key_type'], unique=False)
    # ### end Alembic commands ###
