"""Pydantic schemas package."""
from app.schemas.common import (
    PaginatedResponse,
    PaginationInfo,
)
from app.schemas.api_key import (
    APIKeyBase,
    APIKeyCreate,
    APIKeyDecryptRequest,
    APIKeyDecryptResponse,
    APIKeyInDB,
    APIKeyListResponse,
    APIKeyResponse,
    APIKeyUpdate,
    FormatType,
)
from app.schemas.connection import (
    ColumnSchema,
    ForeignKeySchema,
    TableSchema,
    ConnectionBase,
    ConnectionCreate,
    ConnectionUpdate,
    ConnectionInDB,
    ConnectionResponse,
    ConnectionTestRequest,
    ConnectionTestResponse,
    SchemaResponse,
    SchemaRefreshResponse,
)
from app.schemas.evaluation import (
    EvalTaskCreate,
    EvalTaskUpdate,
    EvalTaskResponse,
    EvalTaskListResponse,
    EvalResultResponse,
    EvalResultListResponse,
    EvalProgressResponse,
    EvalStatsResponse,
    DatasetQuestion,
    DatasetLoadResponse,
    EvalTaskStats,
)
from app.schemas.query import (
    QueryGenerateRequest,
    QueryExecuteRequest,
    QueryRunRequest,
    QueryGenerateResponse,
    QueryExecuteResponse,
    QueryRunResponse,
    QueryHistoryItem,
    QueryHistoryListResponse,
    QueryResultData,
    ToggleFavoriteResponse,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserInDB,
    UserResponse,
    UserLogin,
    PasswordChange,
    Token,
    TokenWithUser,
    TokenPayload,
)

__all__ = [
    # Common schemas
    "PaginatedResponse",
    "PaginationInfo",
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    "UserResponse",
    "UserLogin",
    "PasswordChange",
    "Token",
    "TokenWithUser",
    "TokenPayload",
    # Connection schemas
    "ColumnSchema",
    "ForeignKeySchema",
    "TableSchema",
    "ConnectionBase",
    "ConnectionCreate",
    "ConnectionUpdate",
    "ConnectionInDB",
    "ConnectionResponse",
    "ConnectionTestRequest",
    "ConnectionTestResponse",
    "SchemaResponse",
    "SchemaRefreshResponse",
    # API Key schemas
    "APIKeyBase",
    "APIKeyCreate",
    "APIKeyUpdate",
    "APIKeyInDB",
    "APIKeyResponse",
    "APIKeyListResponse",
    "APIKeyDecryptRequest",
    "APIKeyDecryptResponse",
    "FormatType",
    # Query schemas
    "QueryGenerateRequest",
    "QueryExecuteRequest",
    "QueryRunRequest",
    "QueryGenerateResponse",
    "QueryExecuteResponse",
    "QueryRunResponse",
    "QueryHistoryItem",
    "QueryHistoryListResponse",
    "QueryResultData",
    "ToggleFavoriteResponse",
    # Evaluation schemas
    "EvalTaskCreate",
    "EvalTaskUpdate",
    "EvalTaskResponse",
    "EvalTaskListResponse",
    "EvalResultResponse",
    "EvalResultListResponse",
    "EvalProgressResponse",
    "EvalStatsResponse",
    "DatasetQuestion",
    "DatasetLoadResponse",
    "EvalTaskStats",
]
